"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { ScrollArea } from "@/components/ui/scroll-area"
import { useToast } from "@/hooks/use-toast"
import { Textarea } from "@/components/ui/textarea"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { FileText, Download, Save } from "lucide-react"

export default function PRDGeneratorPage() {
  const [prdContent, setPrdContent] = useState("")
  const [clientName, setClientName] = useState("")
  const [projectName, setProjectName] = useState("")
  const [loading, setLoading] = useState(false)
  const { toast } = useToast()

  const handleGeneratePRD = async () => {
    if (!clientName || !projectName) {
      toast({
        title: "Missing information",
        description: "Please provide client name and project name",
        variant: "destructive",
      })
      return
    }

    setLoading(true)

    try {
      // Simulate PRD generation
      setTimeout(() => {
        const generatedPRD = `# Project Requirements Document
## ${projectName}
### Client: ${clientName}

## 1. Project Overview
This is a sample PRD generated for ${clientName}'s ${projectName} project. In the actual implementation, this would be generated by the PRD agent based on the conversation with the client.

## 2. Objectives
- Objective 1
- Objective 2
- Objective 3

## 3. Requirements
### Functional Requirements
- Requirement 1
- Requirement 2
- Requirement 3

### Non-Functional Requirements
- Performance
- Security
- Scalability

## 4. Timeline
- Phase 1: Planning (2 weeks)
- Phase 2: Development (4 weeks)
- Phase 3: Testing (2 weeks)
- Phase 4: Deployment (1 week)

## 5. Budget
$XX,XXX - $XX,XXX

## 6. Stakeholders
- ${clientName} (Client)
- TDX Project Manager
- TDX Development Team

Generated on: ${new Date().toLocaleDateString()}`

        setPrdContent(generatedPRD)
        setLoading(false)

        toast({
          title: "PRD Generated",
          description: "PRD has been successfully generated",
        })
      }, 2000)

      // In the actual implementation, we would call the PRD agent API here
      // const response = await fetch("/api/generate-prd", {
      //   method: "POST",
      //   headers: { "Content-Type": "application/json" },
      //   body: JSON.stringify({ clientName, projectName }),
      // });
      // const data = await response.json();
      // setPrdContent(data.prd);
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to generate PRD",
        variant: "destructive",
      })
    } finally {
      setLoading(false)
    }
  }

  const handleSavePRD = async () => {
    toast({
      title: "PRD Saved",
      description: "PRD has been saved to the database",
    })
  }

  const handleDownloadPRD = () => {
    const element = document.createElement("a")
    const file = new Blob([prdContent], { type: "text/markdown" })
    element.href = URL.createObjectURL(file)
    element.download = `${projectName.replace(/\s+/g, "-").toLowerCase()}-prd.md`
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  return (
    <div className="flex flex-col gap-6">
      <h1 className="text-3xl font-bold">PRD Generator</h1>

      <div className="grid grid-cols-12 gap-6">
        <div className="col-span-12 md:col-span-4">
          <Card>
            <CardHeader>
              <CardTitle>Project Information</CardTitle>
              <CardDescription>Enter the details to generate a PRD</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="clientName">Client Name</Label>
                <Input
                  id="clientName"
                  placeholder="Enter client name"
                  value={clientName}
                  onChange={(e) => setClientName(e.target.value)}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="projectName">Project Name</Label>
                <Input
                  id="projectName"
                  placeholder="Enter project name"
                  value={projectName}
                  onChange={(e) => setProjectName(e.target.value)}
                />
              </div>
              {/* Additional fields would go here */}
            </CardContent>
            <CardFooter>
              <Button onClick={handleGeneratePRD} disabled={loading} className="w-full">
                {loading ? "Generating..." : "Generate PRD"}
              </Button>
            </CardFooter>
          </Card>

          <Card className="mt-6">
            <CardHeader>
              <CardTitle>PRD Templates</CardTitle>
              <CardDescription>Select a template to start with</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                <Button variant="outline" className="w-full justify-start">
                  <FileText className="mr-2 h-4 w-4" />
                  Standard PRD Template
                </Button>
                <Button variant="outline" className="w-full justify-start">
                  <FileText className="mr-2 h-4 w-4" />
                  Detailed PRD Template
                </Button>
                <Button variant="outline" className="w-full justify-start">
                  <FileText className="mr-2 h-4 w-4" />
                  Minimal PRD Template
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="col-span-12 md:col-span-8">
          <Card className="h-[calc(100vh-220px)] flex flex-col">
            <CardHeader>
              <div className="flex justify-between items-center">
                <div>
                  <CardTitle>PRD Editor</CardTitle>
                  <CardDescription>Edit and preview the generated PRD</CardDescription>
                </div>
                <div className="flex gap-2">
                  <Button variant="outline" onClick={handleSavePRD}>
                    <Save className="mr-2 h-4 w-4" />
                    Save
                  </Button>
                  <Button variant="outline" onClick={handleDownloadPRD}>
                    <Download className="mr-2 h-4 w-4" />
                    Download
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent className="flex-1 overflow-hidden">
              <Tabs defaultValue="edit" className="h-full">
                <TabsList className="grid grid-cols-2">
                  <TabsTrigger value="edit">Edit</TabsTrigger>
                  <TabsTrigger value="preview">Preview</TabsTrigger>
                </TabsList>
                <TabsContent value="edit" className="h-[calc(100%-40px)]">
                  <Textarea
                    className="h-full resize-none font-mono"
                    placeholder="PRD content will appear here"
                    value={prdContent}
                    onChange={(e) => setPrdContent(e.target.value)}
                  />
                </TabsContent>
                <TabsContent value="preview" className="h-[calc(100%-40px)]">
                  <ScrollArea className="h-full pr-4">
                    <div className="prose dark:prose-invert max-w-none">
                      {prdContent ? (
                        <pre className="whitespace-pre-wrap">{prdContent}</pre>
                      ) : (
                        <div className="h-full flex items-center justify-center text-gray-500">
                          <p>Generate a PRD to see the preview</p>
                        </div>
                      )}
                    </div>
                  </ScrollArea>
                </TabsContent>
              </Tabs>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
